services:
  telegram-youtube-downloader:
    build: .
    restart: unless-stopped
    environment:
      - TELEGRAM_BOT_KEY
      - YOUTUBE_API_KEY
    volumes:
      - ./docker/configs:/app/telegram_youtube_downloader/configs
      - ./docker/logs:/app/logs
      - ./docker/temp:/app/temp
